# Generated by Django 3.1.7 on 2021-08-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danh_ba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhba',
            name='canbo',
        ),
        migrations.AddField(
            model_name='canbo',
            name='danh_ba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_ba.danhba'),
        ),
        migrations.AddField(
            model_name='danhba',
            name='ten',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CanBoDanhBa',
        ),
    ]
